apiVersion: v1
kind: Namespace
metadata:
  name: desk-reservation-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-python
  namespace: desk-reservation-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-python
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "python-instrumentation"
      labels:
        app: backend-python
    spec:
      containers:
      - name: backend-python
        image: gzarba/desk-reservation-app:backend-python
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
          - name: FLASK_APP
            value: "app.py"
          - name: FLASK_ENV
            value: "development"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-python
  namespace: desk-reservation-app
spec:
  selector:
    app: backend-python
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: desk-reservation-app
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: gzarba/desk-reservation-app:mysql
        ports:
        - containerPort: 3306
