apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python-instrumentation
  namespace: desk-reservation-app
spec:
  exporter:
    endpoint: http://otel-collector-daemonset-collector.otel-collector.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      - name: OTEL_PYTHON_LOG_CORRELATION
        value: 'true'

